name: CD - Deploy to Minikube using GitHub Actions

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Minikube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Check Minikube Cluster
        run: kubectl get pods -A

      - name: Build Docker Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t doc-k8s-example:v2.11.3 .
          docker images

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl wait --for=condition=Ready pod -l app=doc-k8s-example --timeout=120s
          kubectl get all

      - name: Test Service
        run: |
          echo "SERVICE_URL=$(minikube service doc-k8s-example --url)"
          kubectl port-forward service/doc-k8s-example 8080:8080 &> /dev/null &
          sleep 5
          curl -i http://localhost:8080/

      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete
